### ISSUE TITLE
Log hcat dependency size

### ISSUE THREAD

**Issue by findkim** [hashicorp/consul-terraform-sync#149]
#### Description
Add trace logging on the size of hcat dependencies watched, similar to Consul Template ([source code](https://github.com/hashicorp/consul-template/blob/7714a546e53f56b630aa1ba311a1242c1062f121/manager/runner.go#L225-L231)) without being too noisy.

#### Use Cases
This would help debug issues for Consul Terraform Sync reaching Consul API limits and DDoS https://github.com/hashicorp/consul-terraform-sync/issues/146

**Comment by eikenb** [comment]
Aside from logging this, we might want to make a longer term note of looking into ways of limiting the number of connections used. Seems that HTTP-2 connections and/or pooling could be used to reduce this number.

**Comment by findkim** [comment]
I'm finding that pooling is likely a factor of #146, it's the default transport option used in hcat ([hcat source](https://github.com/hashicorp/hcat/blob/master/internal/dependency/client_set.go#L76) | [consul source](https://github.com/hashicorp/consul/blob/master/api/api.go#L365-L367)). The pooled transport holds on to a connection for 90s ([source code](https://github.com/hashicorp/go-cleanhttp/blob/master/cleanhttp.go#L32)) and paired with a large number of connections being made likely causes quickly reaching Consul connection limits. I think focusing on reducing the number of calls or making use of the pooled client connection would be ideal.
