### ISSUE TITLE
Switch to using structured logging

### ISSUE THREAD

**Issue by lornasong** [hashicorp/consul-terraform-sync#177]
#### Description
Update CTS logging to use [go-hclog](https://github.com/hashicorp/go-hclog)

#### Use Cases
Structured logs will support more ways for users to interact with logs such as filtering and using observability platforms

**Comment by findkim** [comment]
Looks completed! Closing this out: https://github.com/hashicorp/consul-terraform-sync/pull/373 @wilkermichael
