### ISSUE TITLE
Setup TF printer client log to filter log levels

### ISSUE THREAD

**Issue by findkim** [hashicorp/consul-terraform-sync#23]
The printer client is used for testing purposes to circumvent executing the TF CLI when not needed. It uses a different logger from the global logger to isolate for unit tests. It would be ideal to have this client's logger to also be configured to filter the same log levels as the global one does on startup.

**Comment by wilkermichael** [comment]
`INFO` is a good default for learning a tool, `WARN` is a good production default. Our tools generally are fairly simple to understand and pick up and so having a production level default is nice to keep the configurations smaller and avoid log spam. However, as CTS evolves with more features, and given the general consensus from the team that our `INFO` logs don't over-flood the console, we have decided to go ahead an change the default log level to `INFO`
