### ISSUE TITLE
Multiple tasks with same service updates resources inconsistently

### ISSUE THREAD

**Issue by lornasong** [hashicorp/consul-terraform-sync#234]
### Describe the bug
I configured multiple tasks with the same service and same module. When I manually register and deregister service instances, initially the tasks trigger and update resources as expected. At some point that is inconsistent, only one task will trigger to update resources while other tasks stay dormant. Once this happens, all subsequent register and deregistering only trigger that one task. The `terraform.tfvars` confirms this - the one task's tfvars will have the updated service information while the other tasks' tfvars will have outdated information.

### Versions
**Consul Terraform Sync**
```
consul-terraform-sync 0.1.0-beta (6ef6680)
Compatible with Terraform >= 0.13.0, < 0.15
```

**Consul Version**
```
Consul 1.9.4
```

**Terraform Version**
```
Terraform v0.14.8
```

### Configuration File(s)
<details>
<summary>Click to toggle contents of config file </summary>

```hcl
log_level = "info"

consul {
  address = "localhost:8500"
}

driver "terraform" {
  log = true
  working_dir = "build"
}

task {
  name = "task_c"
  services = ["api"]
  version = "0.0.1"
  source = "lornasong/cts_file/local"
}

task {
  name = "task_d"
  services = ["api"]
  version = "0.0.1"
  source = "lornasong/cts_file/local"
}

task {
  name = "task_e"
  services = ["api"]
  version = "0.0.1"
  source = "lornasong/cts_file/local"
}
```
</details>

### Expected Behavior
Expect all tasks to be triggered by service instance registering or deregistering consistently

### Actual Behavior
After some time, only one task is triggered by service instance registering or deregistering

Logs below: I registered service instance "api1". In the logs, you can see that all 3 tasks are triggered and create a resource. I then deregistered "api1". In the logs, you can see that only task_d is triggered

<details>
<summary>Sample logs </summary>
2021/03/24 15:35:52.639624 [INFO] (ctrl) executing task task_e
2021/03/24 15:35:52.639699 [INFO] (ctrl) executing task task_c
2021/03/24 15:35:52.639723 [INFO] running Terraform command: /Users/lornasong/go/src/github.com/hashicorp/consul-terraform-sync/terraform apply -no-color -auto-approve -input=false -var-file=terraform.tfvars -var-file=providers.tfvars -lock=true -parallelism=10 -refresh=true
2021/03/24 15:35:52.639727 [INFO] (ctrl) executing task task_d
2021/03/24 15:35:52.639757 [INFO] running Terraform command: /Users/lornasong/go/src/github.com/hashicorp/consul-terraform-sync/terraform apply -no-color -auto-approve -input=false -var-file=terraform.tfvars -var-file=providers.tfvars -lock=true -parallelism=10 -refresh=true
2021/03/24 15:35:52.639802 [INFO] running Terraform command: /Users/lornasong/go/src/github.com/hashicorp/consul-terraform-sync/terraform apply -no-color -auto-approve -input=false -var-file=terraform.tfvars -var-file=providers.tfvars -lock=true -parallelism=10 -refresh=true
module.task_c.local_file.address["api1.web.dc1"]: Creating...
module.task_d.local_file.address["api1.web.dc1"]: Creating...
module.task_e.local_file.address["api1.web.dc1"]: Creating...
module.task_d.local_file.address["api1.web.dc1"]: Creation complete after 0s [id=4b84b15bff6ee5796152495a230e45e3d7e947d9]
module.task_c.local_file.address["api1.web.dc1"]: Creation complete after 0s [id=4b84b15bff6ee5796152495a230e45e3d7e947d9]
module.task_e.local_file.address["api1.web.dc1"]: Creation complete after 0s [id=4b84b15bff6ee5796152495a230e45e3d7e947d9]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
2021/03/24 15:35:53.403520 [INFO] (ctrl) task completed task_d
2021/03/24 15:35:53.403608 [INFO] (ctrl) task completed task_e
2021/03/24 15:35:53.403744 [INFO] (ctrl) task completed task_c
2021/03/24 15:36:09.500976 [INFO] (ctrl) executing task task_d
2021/03/24 15:36:09.501062 [INFO] running Terraform command: /Users/lornasong/go/src/github.com/hashicorp/consul-terraform-sync/terraform apply -no-color -auto-approve -input=false -var-file=terraform.tfvars -var-file=providers.tfvars -lock=true -parallelism=10 -refresh=true
module.task_d.local_file.address["api1.web.dc1"]: Refreshing state... [id=4b84b15bff6ee5796152495a230e45e3d7e947d9]
module.task_d.local_file.address["api1.web.dc1"]: Destroying... [id=4b84b15bff6ee5796152495a230e45e3d7e947d9]
module.task_d.local_file.address["api1.web.dc1"]: Destruction complete after 0s

Apply complete! Resources: 0 added, 0 changed, 1 destroyed.
2021/03/24 15:36:10.155385 [INFO] (ctrl) task completed task_d
</details>

### Steps to Reproduce
To register: `curl --header "Content-Type: application/json"   --request PUT   --data '{"ID":"api6","name":"api","port":8086}'   http://localhost:8500/v1/agent/service/register`
To deregister: `curl --header "Content-Type: application/json"   --request PUT   http://localhost:8500/v1/agent/service/deregister/api1`

1. Run Consul: `consul agent -dev`
2. Run CTS with above configuration: `consul-terraform-sync -config-file=config.hcl`
3. Register service instance api1
4. See resources are created for all tasks
5. Deregister service instance api1
6. See maybe only one task is triggered to destroy resource.

If the above steps don't reproduce the issue, continuing to register service instances and deregister will eventually lead to the issue. Deregistering seems most consistent in reproducing the issue. However, registering does reproduce the issue as well.

**Comment by eikenb** [comment]
I wonder if this is related to what I'm seeing with the benchmarks in https://github.com/hashicorp/consul-terraform-sync/pull/232#discussion_r598936666

**Comment by findkim** [comment]
that's a surprise to me that another repo could close out this issue.
