### ISSUE TITLE
Regex support for service trigger

### ISSUE THREAD

**Issue by findkim** [hashicorp/consul-terraform-sync#299]
#### Description
Allow user to specify a regex to match the service name in Consul catalog within the task configuration block. Task should be triggered for any changes to the service matching the regex in the Consul catalog. Current implementation of CTS for a service trigger needs the entire service name to be specified in the `task.services` list.

```hcl
task {
  name = "my-task"
  services = ["web", "web-sidecar-proxy", "web-microservice1", "web-microservice2"]
}
```

#### Use Cases
CTS to automate Terraform for discovered services registered with the Consul catalog without requiring to explicitly update CTS configuration (which requires restarting CTS).

#### Alternative Solutions
```hcl
task {
  name = "my-task"
  services = []
  conditions {
    regexp = "^web.*"
  }
}
```

#### Additional context
How would a user know the names of service that match the regex?

**Comment by sofixa** [comment]
That would be a really useful feature, especially when Consul services are automatically registered by an orchestrator ( like Nomad).

**Comment by mkam** [comment]
The regex support has been added, and support for query parameters in addition to the regex will be handled in a follow up feature (https://github.com/hashicorp/consul-terraform-sync/issues/357).
