### ISSUE TITLE
Disabled tasks do not trigger after re-enabling

### ISSUE THREAD

**Issue by lornasong** [hashicorp/consul-terraform-sync#320]
### Describe the bug
After a task that was disabled is re-enabled using the cli, the task should trigger when its condition is met. However, the task is not triggered even though the dependency change is identified by CTS.

### Versions
**Consul Terraform Sync**
```
consul-terraform-sync v0.1.0-175-gc5016b5 (c5016b5)
Compatible with Terraform >= 0.13.0, < 0.16
```

### Configuration File(s)
_Reminder to redact any sensitive information that may be present in this file_

<details>
<summary>Click to toggle contents of config file </summary>

```hcl
log_level = "TRACE"

consul {
  address = "localhost:8500"
}

driver "terraform" {
  log = true
  working_dir = "build/testing"
}

task {
  name = "task_c"
  source      = "./build/modules/catalog-services"
  condition "catalog-services" {
      regexp = "api"
      source_includes_var = true
  }
}
```
</details>

### Terraform Module
<details>
<summary>Click to toggle main.tf</summary>

```hcl
resource "local_file" "tags" {
    for_each = var.catalog_services
    content = join(", ", each.value)
    filename = "resources/tags_${each.key}.txt"
}
```
</details>

<details>
<summary>Click to toggle variables.tf</summary>

```hcl
variable "services" {
  description = "Consul services monitored by Consul Terraform Sync"
  type = map(
    object({
      id        = string
    })
  )
}

variable "catalog_services" {
  description = "Consul catalog service names and list of all known tags for a given service"
  type = map(list(string))
}
```
</details>

### Expected Behavior
When the task is re-enabled and a new service is registered, the task is triggered and creates the resource.

### Actual Behavior
When the task is re-enabled and a new service is registered, the task is not triggered.

Example logs:
```
// ... task was enabled
2021/06/18 21:17:06.432995 [DEBUG] (notifier.cs) received dependency change type []*dep.CatalogSnippet
2021/06/18 21:17:06.433031 [DEBUG] (notifier.cs) notify registration change
2021/06/18 21:17:06.433172 [TRACE] (driver.terraform) checking dependency changes for task task_c
2021/06/18 21:17:11.435207 [TRACE] (driver.terraform) checking dependency changes for task task_c
```
In the above logs, I registered a service that meets the condition of task_c. The notifier sent a notification for the registration. The driver checks for the change but does not render and execute the template.

### Steps to Reproduce
1. Run Consul: `consul agent -dev`
2. Run CTS with config above: `consul-terraform-sync -config-file=config.hcl`
3. Disable task: `consul-terraform-sync task disable task_c`
4. Re-enable task: `consul-terraform-sync task enable task_c`
5. Register a new service that meets the condition: `consul services register -id=api-web -name=api-web`
6. Observe in CTS logs that the task was not triggered and resources not created

**Comment by findkim** [comment]
A related bug was found once this was resolved: the API sever would race against the controller's main loop. Resolved here https://github.com/hashicorp/consul-terraform-sync/pull/344
