### ISSUE TITLE
Support remote operations for CTS on Terraform Enterprise 

### ISSUE THREAD

**Issue by devarshishah3** [hashicorp/consul-terraform-sync#327]
#### Description
Allow Terraform Enterprise to support remote operations for CTS Tasks

#### Use Cases
Terraform Enterprise provides infrastructure operators the ability to support audit logging, secure state store, secure variable management, consistent environments to drive automation, approval workflows and notifications. These capabilities allow enterprises to streamline internal processes and demonstrate ongoing accountability to regulators for the changes made to the networking infrastructure using Terraform Enterprise. 

Supporting remote operations for CTS on Terraform Enterprise will allow operators to integrate their CTS driven workflows for automating infrastructure into their organization's existing operational process.

**Comment by findkim** [comment]
released 😁 https://discuss.hashicorp.com/t/consul-terraform-sync-v0-3-0-oss-and-enterprise/29006
