### ISSUE TITLE
Support remote operations for CTS on Terraform Cloud

### ISSUE THREAD

**Issue by devarshishah3** [hashicorp/consul-terraform-sync#328]
Description
Allow Terraform Cloud to support remote operations for CTS Tasks

Use Cases
Terraform Cloud provides infrastructure operators the ability to support audit logging, secure state store, secure variable management, consistent environments to drive automation, approval workflows and notifications. These capabilities allow enterprises to streamline internal processes and demonstrate ongoing accountability to regulators for the changes made to the networking infrastructure using Terraform Cloud.

Supporting remote operations for CTS on Terraform Cloud will allow operators to integrate their CTS driven workflows for automating infrastructure into their organization's existing operational process.

**Comment by lornasong** [comment]
Released with 0.4.0+ent-beta1 ([announcement](https://discuss.hashicorp.com/t/consul-terraform-sync-v0-4-0-beta1-oss-and-enterprise/30073))
