### ISSUE TITLE
Deprecate port CLI option

### ISSUE THREAD

**Issue by mkam** [hashicorp/consul-terraform-sync#498]
#### Description
The option `-http-addr` was added to the CLI as part of implementing TLS on the CTS API (https://github.com/hashicorp/consul-terraform-sync/pull/490). This allows users to specify the whole address of the CTS API, including the port, so `-port` should be deprecated in favor of `-http-addr`.

**Comment by jwair** [comment]
Added warning when port CLI option is used
https://github.com/hashicorp/consul-terraform-sync/pull/617

**Comment by jwair** [comment]
#617
