### ISSUE TITLE
cts_user_defined_meta not showing up in terraform.tfvars

### ISSUE THREAD

**Issue by jyipks** [hashicorp/consul-terraform-sync#698]
### Describe the bug
cts_user_defined_meta does not appear to be passed onto the services variable. i would like to use data in those fields, but after reviewing terraform.tfvars it does not appear to be getting through.

### Versions
**Consul Terraform Sync**
```
consul-terraform-sync v0.4.3
```

**Consul Version**
```
Consul 1.11.3
```

**Terraform Version**
```
Terraform v1.1.6
```

### Configuration File(s)
_Reminder to redact any sensitive information that may be present in this file_

<details>
<summary>Click to toggle contents of config file </summary>

```hcl
log_level = "INFO"
port = 8558

buffer_period {
  enabled = true
  min = "5s"
  max = "20s"
}

consul {
  address = "consul.service.consul:8500"
}

service {
  name = "abc_rest"
  filter = "\"dev\" in Service.Tags"
  datacenter = "dc1"
  description = "abc_rest test"
  cts_user_defined_meta = {
      vserver-name = "vs-web",
      vport = 80,
      vprotocol = "tcp"
      vip = "10.10.10.10"
  }
}

service {
  name = "adc_svc"
  datacenter = "dc1"
  description = "Sample service for demo purposes"
}

task {
  name = "adc_task"
  description = "Sync services to ADC"
  enabled = true,
  providers = ["citrixadc"]
  services = ["abc_rest"]
  source = "./terraform-citrixadc-servicegroup-consul-sync-nia"
  variable_files = []
}

driver "terraform" {
  log = true

  required_providers {
    citrixadc = {
      source = "citrix/citrixadc"
    }
  }
}

terraform_provider "citrixadc" {
  endpoint = "https://xx"
  username = "xx"
  password = "xx"
  insecure_skip_verify = true
}

```
</details>

### Terraform Configuration Files Generated by Consul-Terraform-Sync
_Reminder to redact any sensitive information that may be present in the files_

<details>
<summary>Click to toggle contents of main.tf </summary>

```terraform
# This file is generated by Consul Terraform Sync.
#
# The HCL blocks, arguments, variables, and values are derived from the
# operator configuration for Sync. Any manual changes to this file
# may not be preserved and could be overwritten by a subsequent update.
#
# Task: adc_task
# Description: Sync services to ADC

terraform {
  required_version = ">= 0.13.0, < 1.2.0"
  required_providers {
    citrixadc = {
      source = "citrix/citrixadc"
    }
  }
  backend "consul" {
    address = "consul.service.consul:8500"
    gzip    = true
    path    = "consul-terraform-sync/terraform"
  }
}

provider "citrixadc" {
  endpoint             = var.citrixadc.endpoint
  insecure_skip_verify = var.citrixadc.insecure_skip_verify
  password             = var.citrixadc.password
  username             = var.citrixadc.username
}

# Sync services to ADC
module "adc_task" {
  source   = "/home/jyip/nia/terraform-citrixadc-servicegroup-consul-sync-nia"
  services = var.services
}

```
</details>

<details>
<summary>Click to toggle contents of terraform.tfvars </summary>

```terraform
services = {
  abc_rest.node01.dc1" = {
    id      = "abc_rest"
    name    = "abc_rest"
    kind    = ""
    address = "10.0.6.110"
    port    = 11301
    meta = {
      registrationType = "config"
      serviceName      = "abc"
    }
    tags            = ["dev"]
    namespace       = ""
    status          = "passing"
    node            = "node01"
    node_id         = "153ec69c-506d-4995-f336-ecd6b6f285fa"
    node_address    = "10.0.6.110"
    node_datacenter = "dc1"
    node_tagged_addresses = {
      lan      = "10.0.6.110"
      lan_ipv4 = "10.0.6.110"
      wan      = "10.0.6.110"
      wan_ipv4 = "10.0.6.110"
    }
    node_meta = {
      consul-network-segment = ""
    }
    cts_user_defined_meta = {}
  },
}
```
</details>

### Terraform Module
servicegroup-consul-sync-nia

### Expected Behavior
i expect the cts_user_defined_meta values to be passed through, so they can be used in the module, tested this on ubuntu 18.04 and windows 2016 server. same issue.

### Actual Behavior
as showing in the terraform.tfvars file, cts_user_defined_meta remains empty

### Steps to Reproduce
1. consul-terraform-sync -config-file config.hcl

**Comment by jyipks** [comment]
after some debugging, found the issue in my environment. unfortunately the sanitized version of my files would make it hard to find the issue.

The issue is case sensitivity for the service name in config.hcl, it accepts all lowercase, but causes serviceMeta variable to not get populated if it doesnt match what it returns from Consul.

**Comment by lornasong** [comment]
Hi @jyipks! Thanks so much for opening this issue and documenting your resolution. Appreciate it!

Not sure if this can be applied to your use-case, but wanted to mention just in case its useful. We've recently added in 0.5.0 the ability to configure `condition "services"` with a list of names and the same parameters as the `service` block. You would be able to combine the services-related configuration in one block, which might help avoid cross-config mis-matches due to case-sensitivity (example below). Feel free reach out with any questions. Thanks!

```diff
-service {
- name = "abc_rest"
- filter = "\"dev\" in Service.Tags"
- datacenter = "dc1"
- description = "abc_rest test"
- cts_user_defined_meta = {
-     vserver-name = "vs-web",
-     vport = 80,
-     vprotocol = "tcp"
-     vip = "10.10.10.10"
- }
-}

task {
  name = "adc_task"
  description = "Sync services to ADC"
  enabled = true,
  providers = ["citrixadc"]
- services = ["abc_rest"]
  source = "./terraform-citrixadc-servicegroup-consul-sync-nia"
+ condition "services" {
+   names = ["abc_rest"]
+   filter = "\"dev\" in Service.Tags"
+   datacenter = "dc1"
+   description = "abc_rest test"
+   cts_user_defined_meta = {
+       vserver-name = "vs-web",
+       vport = 80,
+       vprotocol = "tcp"
+       vip = "10.10.10.10"
+   }
  }
}
```

**Comment by lornasong** [comment]
Yes, you're right. With this new configuration format, you would unfortunately have to break it into different individual tasks. Here's an [example](https://www.consul.io/docs/nia/release-notes/0-5-0#deprecate-service-block) of something similar to what you're describing.

We don't have a lot of information about how people are using `cts_user_defined_meta`. If you have feedback about this design and problems with splitting into multiple tasks, please don't hesitate to let us know! Currently, we are thinking of [providing users a way to upgrade](https://github.com/hashicorp/consul-terraform-sync/issues/733) their configuration. This solution could potentially automatically break up a task into different individual tasks.

Just to be sure though, your current configuration with the `services` field and `service` block is still supported in 0.5.0. So you would be able to still use your current configuration in 0.5.0.
