### ISSUE TITLE
Notifier does not complete once-mode for new tasks through Create Task API

### ISSUE THREAD

**Issue by lornasong** [hashicorp/consul-terraform-sync#704]
### Describe the bug
When a task is created via the API that shares a dependency with an existing task, the created task may unexpectedly be triggered. This is because the notifier for the created task does not complete once-mode, so the task will trigger on incoming dependency changes without checking if that change satisfies the task's trigger conditions.

In the case of catalog-service condition, this can cause the create request to hang and time out if there are no services registered.

### Versions
**Consul Terraform Sync**
Seen as part of development of 0.5.0. The create task API is a new feature of 0.5.0, so this will not be seen in any previous versions.

### Configuration File(s)
```hcl
task {
  name = "test-task"
  module = "mkam/hello/cts"
  condition "services" {
    names = ["api", "web"]
  }
}
```

Request
```
POST /v1/tasks

{
   "task": {
       "condition": {
           "catalog_services": {
               "regexp": "web"
           }
       },
       "module_input": {
           "services": {
               "names": [
                   "api"
               ]
           }
       },
       "name": "a_ls_api_cs",
       "module": "lornasong/cts_cs_file/local",
       "version": "0.0.1"
   }
}
```

### Expected Behavior
Request should be successful and the created task should only trigger when the task condition is met.

### Actual Behavior
Excluding the specific catalog-service scenario, the task is created successfully but is always triggered on a dependency change. With a catalog-service condition and no services registered that satisfy the catalog-service regexp, the request will time out and the task will not be created.

### Steps to Reproduce
1. Configure and start CTS with a task that has `api`  in the `module_input "services"`
2. Create a new task that has a Consul KV condition and also has `api` as the services module input.
3. Make a change to the `api` service. 

The created task will be triggered even though it's only supposed to be triggered by Consul KV changes. Subsequent changes to the `api` service will be ignored as expected since at this point, once-mode will have been completed for that task.

**Comment by mkam** [comment]
We implemented a short-term fix for this which will always set once-mode to complete. A long term fix will be implemented separately in the future so that the task will naturally complete once-mode rather than us setting it.
