### ISSUE TITLE
Service state change during task execution can cause locked state

### ISSUE THREAD

**Issue by wilkermichael** [hashicorp/consul-terraform-sync#732]
### Describe the bug
If a task is executed, and a service which triggers that task changes state while the task is executing, the TFC driver enters a locked state. Terraform CLI does not lock up, however, changes which happens while the task is running are ignored. 

**Note**
- This only affects Tasks when a change to a resource, monitored by these Tasks, is made while these Tasks are running. Tasks monitoring different resources, and newly created tasks, regardless of which resource they're monitoring, will work as intended.

### Versions
**Consul Terraform Sync**
```
consul-terraform-sync-enterprise >= v0.5.0
```

**Consul Version**
```
Tested with Consul v1.11.3
```

**Terraform Version**
```
Tested with Terraform v1.1.6
```

### Expected Behavior
If a service changes state during task execution, where the task is triggered by the service which changes state, then after the task completes a new task execution should take place.

### Actual Behavior
CTS logs an event, and then will no longer trigger on service changes for that particular task:

```
2022-02-24T09:49:01.011-0800 [INFO]  ctrl: task completed: task_name=michael-github-task
2022-02-24T09:49:01.011-0800 [TRACE] ctrl: adding event: event="&Event{ID:633d74eb-94e1-deff-333b-a57e7ead7a1c, TaskName:michael-github-task, Success:true, StartTime:2022-02-24 09:48:34.148593 -0800 PST m=+22.755140190, EndTime:2022-02-24 09:49:01.011806 -0800 PST m=+49.618325080, EventError:%!s(*event.Error=<nil>), Config:&Config{Providers:[local], Services:[web api], Source:./git-module}}"
```

### Steps to Reproduce
1. Start CTS with a task that triggers on a service change
2. Change the state of the service (Deregister or Register, whatever is opposite of the current state)
3. While CTS is executing the task, change the state again
4. Once the event is logged, observe that no changes to task trigger the task

### Additional Context

- attempted to create a task with and without enabled buffer_period. Issue exists in both cases, buffer_period settings do not seem to have an effect.
- have not tested with tasks triggering on non-service conditions (catalog-services, consul-kv, etc.). So may effect tasks triggering on other conditions as well.

**Comment by wilkermichael** [comment]
##OSS Research
- Previously (as in 0.4.3 and earlier), when any change was detected, we would try to [run all dynamic tasks](https://github.com/hashicorp/consul-terraform-sync/blob/v0.4.3/controller/readwrite.go#L79-L93) and [wait for them to complete](https://github.com/hashicorp/consul-terraform-sync/blob/v0.4.3/controller/readwrite.go#L134). If a change happened while a task was running, it would be executed after the current run had completed.
This also meant that if task_a was running, and a Consul change for task_b was made, task_b would not run until task_a was completed.
- Now in 0.5.0, the watcher returns specifically what template needs updating, so we [only run the task that is monitoring the dependency change](https://github.com/hashicorp/consul-terraform-sync/blob/main/controller/readwrite.go#L108-L115). We also run it as a goroutine, so there's no more waiting for the task to complete.
This has the advantage where task_b can still be triggered immediately even if task_a is currently running.
- Because we're no longer waiting, we start a process to run the task even though it's currently running. This method [checks that the task is active](https://github.com/hashicorp/consul-terraform-sync/blob/main/controller/readwrite.go#L149-L154) and returns without running, which is why the change is ignored completely.
That IsActive check was supposed to ignore runs triggered by the enable API when the task was already in progress.

**Comment by wilkermichael** [comment]
## Enterprise Research

The TFC lockup was caused because of a code change to HCAT:

```Go
func (t *Template) Notify(interface{}) bool {
	select {
	case t.dirty <- struct{}{}:
		return true
	default:
		return false
	}
}
```

The t.dirty channel is written to when new data comes in, because the data was never being executed ([due to the isActive logic](https://github.com/hashicorp/consul-terraform-sync/blob/main/controller/readwrite.go#L149-L154)). The t.dirty channel was never being drained, and Notify was always returning false. TFC uses the hcat template, and the hcat template requires notify to return true before it will write to the watcher channel. Since we wrap the hcat template in our own notifier for the OSS conditions, which doesn't require Template.Notify to return true, the lock-up didn't occur on OSS.

**Comment by mkam** [comment]
Updated name and description to reflect that it's any kind of triggering dependency change and not just services.
