### ISSUE TITLE
Look into using Terraform sensitive attribute

### ISSUE THREAD

**Issue by lornasong** [hashicorp/consul-terraform-sync#85]
Terraform feature to [add sensitive attribute to variables](https://github.com/hashicorp/terraform/pull/26183) is currently slated for version 0.14. This allows adding a `sensitive` attribute to variables which will prevent outputting those variable values during plan. This will be helpful for read-only mode and potentially elsewhere.

**Comment by findkim** [comment]
This would be very impactful to declare the intermediate provider variables as `sensitive` ([example](https://github.com/hashicorp/consul-terraform-sync/blob/master/templates/tftmpl/testdata/variables.tf#L36-L44))
