### ISSUE TITLE
First service change may be ignored after restarting Consul

### ISSUE THREAD

**Issue by mkam** [hashicorp/consul-terraform-sync#884]
### Describe the bug
If Consul is stopped and started while CTS is still running, then sometimes the first monitored service change that happens after Consul has started again is ignored and the task does not trigger. The issue tends to happen more if there is a service registered before CTS is fully initialized.

This was tested with services and not confirmed if it is also happening with other changes like Consul KV.

### Versions
**Consul Terraform Sync**
Confirmed in v0.5.2 and v0.6.0-beta1. Confirmed _not_ in v0.4.3.

### Expected Behavior
After CTS reconnects with Consul, it should monitor changes and trigger tasks.

### Actual Behavior
The first service change is intermittently being ignored. Subsequent changes will cause the task to trigger. 

### Steps to Reproduce
Have not been able to reproduce manually, but was able to reproduce by modifying `TestE2ERestartConsul` to have a service registration done before CTS has initialized. See https://github.com/hashicorp/consul-terraform-sync/commit/dff2d615e3ce81a425e980ee5d4af17e6cb4d72f

### Additional Context
- This was first seen during development of CTS service registration. At that point, CTS was being registered before all tasks had run, and `TestE2ERestartConsul` was failing pretty consistently.
- I'm able to trigger the bug both by having a service registered before starting CTS and registering a service soon after starting CTS (presumably before CTS has fully initialized)
- Timing seems to be a big factor since I'm not able to recreate manually.
- When Consul restarts in the tests, the services are not persisted. This could also be a factor.

**Comment by wilkermichael** [comment]
Related issue: https://github.com/hashicorp/hcat/issues/103
